### ISSUE TITLE
attempting to build examples - objcopy errors

### ISSUE THREAD

**Issue by wideglide** [trailofbits/polytracker#6379]
I'm attempting to build the examples.  I was able to build `file` and `png`, but both `mupdf` and `poppler` fail during the compilation with a bunch of objcopy errors.  Do you have any idea what might be causing this?  
I'm working from `trailofbits/polytracker:latest` which was built three weeks ago.

```
/polytracker/build/bin/polybuild_script -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/compress.o compress.c
/polytracker/build/bin/polybuild_script -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzclose.o gzclose.c
/polytracker/build/bin/polybuild_script -O3 -fPIC -D_LARGEFILE64_SOURCE=1 -DHAVE_HIDDEN  -DPIC -c -o objs/gzread.o gzread.c
objcopy: sti1ieA4: Failed to find link section for section 11
objcopy: sti1ieA4: Failed to find link section for section 11
objcopy: objs/sts2Yj17: Failed to find link section for section 9
objcopy: objs/sts2Yj17: Failed to find link section for section 9
```

However, the final error that aborts the docker build is a file exists error.
```
objcopy: stkOBkmq: Failed to find link section for section 9
cp: cannot create regular file '/build_artifacts/infback.o': File exists
Traceback (most recent call last):
  File "/polytracker/build/bin/polybuild_script", line 475, in <module>
    main()
  File "/polytracker/build/bin/polybuild_script", line 471, in main
    handle_cmd(sys.argv)
  File "/polytracker/build/bin/polybuild_script", line 256, in handle_cmd
    store_artifact(arg_path)
  File "/polytracker/build/bin/polybuild_script", line 207, in store_artifact
    subprocess.check_call(["cp", str(targ_path), str(artifact_file_path)])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cp', '/polytracker/the_klondike/zlib-1.2.11/infback.o', '/build_artifacts/infback.o']' returned non-zero exit status 1.
Makefile:169: recipe for target 'infback.o' failed
```

**Comment by carsonharmon** [comment]
Hi, the ojbcopy issues are normal actually. It just comes with using gllvm. 

The issue you are posting above is known to be a bit flakey, and happens in CI sometimes. We just restart it and it works fine, I believe it is a race condition during parallel builds that I need to fix. 

Could you try rebuilding again?

**Comment by carsonharmon** [comment]
Oh! And if that does not work, please join the Empire Hacking slack. Hop into the #Polytracker and I can help you build the examples.

**Comment by wideglide** [comment]
Ok, that worked for poppler, but maybe there's a related error for `muPDF`?  I get a bunch of `sqlite3.OperationalError: database is locked` errors.

```
make: *** [build/debug/source/fitz/load-gif.o] Error 1
objcopy: build/debug/source/fitz/stO5dASr: Failed to find link section for section 101
objcopy: build/debug/source/fitz/stO5dASr: Failed to find link section for section 101
Traceback (most recent call last):
  File "/polytracker/build/bin/polybuild_script", line 475, in <module>
    main()
  File "/polytracker/build/bin/polybuild_script", line 471, in main
    handle_cmd(sys.argv)
  File "/polytracker/build/bin/polybuild_script", line 263, in handle_cmd
    cur.execute(query)
sqlite3.OperationalError: database is locked
```
