### ISSUE TITLE
Missing 'pytest' dependency

### ISSUE THREAD

**Issue by hbrodin** [trailofbits/polytracker#6485]
I tried the following sequence:
1. Build the polytracker image:
```shell
$ docker build -t trailofbits/polytracker .
...
[+] Building 42.0s (20/20) FINISHED 
```
2. Ceated a new virtual env:
```shell
$ python -m venv poly_venv
$ source poly_venv/bin/activate
```
3. Install developer version of polytracker
```shell
$ python -m pip install -e .
```
4. Tried to run the polytracker image:
```shell
$ polytracker docker run
Traceback (most recent call last):
  File "/Users/.../poly_venv/bin/polytracker", line 33, in <module>
    sys.exit(load_entry_point('polytracker', 'console_scripts', 'polytracker')())
  File "/Users/.../poly_venv/bin/polytracker", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/.../polytracker/__main__.py", line 16, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

Are we missing an explicit dependency on 'pytest'?

**Comment by hbrodin** [comment]
This is already solved by 782ca52d1cec252a1ae6858a671e00730feac072.
